# Generated by Django 2.1.3 on 2018-12-25 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181225_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='store',
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='shop.Store'),
            preserve_default=False,
        ),
    ]
