# Generated by Django 2.1.3 on 2018-12-25 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20181225_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='markett',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='超市名')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('activityTXT', models.CharField(max_length=200, verbose_name='活动信息')),
                ('countTXT', models.CharField(max_length=200, verbose_name='折扣信息')),
                ('image', models.ImageField(blank=True, upload_to='markett')),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('addressTXT', models.CharField(max_length=200, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='男', max_length=10, verbose_name='性别')),
                ('phonenumber', models.CharField(max_length=50, verbose_name='电话号码')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('signature', models.CharField(max_length=200, verbose_name='个人签名')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.AddField(
            model_name='markett',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.user'),
        ),
        migrations.AddField(
            model_name='product',
            name='markett',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='markett', to='shop.markett'),
            preserve_default=False,
        ),
    ]
