# Generated by Django 2.1.3 on 2018-12-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20181225_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markett',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
