# Generated by Django 2.1.3 on 2018-12-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20181225_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='markett',
        ),
    ]
