# Generated by Django 2.1.3 on 2018-12-25 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_markett'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markett',
            options={'ordering': ('name',), 'verbose_name': 'market', 'verbose_name_plural': 'market'},
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='markett', to='shop.markett'),
            preserve_default=False,
        ),
    ]
