# Generated by Django 2.1.3 on 2018-12-25 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20181225_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='market',
        ),
        migrations.AddField(
            model_name='product',
            name='market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='market', to='shop.market'),
            preserve_default=False,
        ),
    ]
