# Generated by Django 2.1.3 on 2018-12-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20181225_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
